// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnzdzneuynkyzfjwheej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBuemR6bmV1eW5reXpmandoZWVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMxNTc4MzgsImV4cCI6MjA0ODczMzgzOH0.BIDaQMOlKZm6IMP4eaiwDCxEgBJ9lzLVu0YuLjrcd_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);